# Generated by Django 4.1.3 on 2022-11-15 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blod', '0003_articl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articl',
            name='categore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blod.blogcategory', verbose_name='категория'),
        ),
    ]
