# Generated by Django 4.1.3 on 2022-11-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_categore_articl_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articl',
            new_name='Article',
        ),
    ]
