# Generated by Django 4.1.3 on 2023-02-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_tag_meta_description_remove_tag_meta_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comment')),
                ('name', models.CharField(max_length=255, verbose_name='User name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Проверено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='coments',
            field=models.ManyToManyField(to='blog.comment', verbose_name='Коментарии'),
        ),
    ]
