# Generated by Django 4.1.3 on 2022-12-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quanity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
    ]
