# Generated by Django 4.1.3 on 2023-01-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_category_meta_description_category_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='meta_keywords',
            new_name='meta_keyword',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='meta_keywords',
            new_name='meta_keyword',
        ),
    ]
