# Generated by Django 4.1.3 on 2023-01-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_rename_meta_keywords_category_meta_keyword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='meta_keyword',
            new_name='meta_keywords',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='meta_keyword',
            new_name='meta_keywords',
        ),
    ]
